sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq verilator python3 python3-setuptools

language: cpp

compiler:
  - clang

install:
  - cd $TRAVIS_BUILD_DIR/tools/xsf_asm && sudo python3 setup.py install

script:
  - cd $TRAVIS_BUILD_DIR/src && make
