dist: xenial
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3 python3-setuptools
  - wget https://github.com/sifive/verilator/releases/download/3.922-0sifive1/verilator_3.922-0sifive1_amd64.deb
  - sudo dpkg -i verilator_3.922-0sifive1_amd64.deb
  - sudo apt-get install -f

language: cpp

compiler:
  - clang

install:
  - cd $TRAVIS_BUILD_DIR/tools/xsf_asm && sudo python3 setup.py install

script:
  - cd $TRAVIS_BUILD_DIR/src && make
  - cd $TRAVIS_BUILD_DIR/tools/xsf_asm && python3 -m unittest discover
