sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3 python3-setuptools
  - git clone http://git.veripool.org/git/verilator
  - cd $TRAVIS_BUILD_DIR/verilator
  - git checkout stable
  - autoconf
  - ./configure
  - make
  - sudo make install

language: cpp

compiler:
  - clang

install:
  - cd $TRAVIS_BUILD_DIR/tools/xsf_asm && sudo python3 setup.py install

script:
  - cd $TRAVIS_BUILD_DIR/src && make
