sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install verilator python3.6

language: cpp

compiler:
  - gcc

install:
  - cd tools/xsf_asm && sudo python3.6 setup.py install

script:
  - cd src && make
