sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install verilator python3 python3-setuptools

language: cpp

compiler:
  - gcc

install:
  - cd tools/xsf_asm && sudo python3 setup.py install

script:
  - cd src && make
